routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlumnosController;
use App\Http\Controllers\EstudiantesController;
use App\Http\Controllers\ProfesoresController;
use App\Http\Controllers\EquiposController;
use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\TiendasController;
use App\Http\Controllers\PiezasController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers;
use App\Http\Controllers\CoordinadoresController;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::view('principal','principal')->name('principal');

//1. Rita que CARGA EL FORMULARIO
Route::get('alumnos',[AlumnosController::class,'create']);
//2. Ruta del post que PROCESA EL FORMULARIO
Route::post('estudiantes',[AlumnosController::class,'store']);

//EQUIPOS
Route::resource('equipos', 'EquiposController');

//EQUIPOS.VIEWS
Route::get('/lista_equipo', function () {
    return view('lista_equipo');
});

Route::get('/agregar_equipo', function () {
    return view('agregar_equipo');
});

Route::get('/editar_equipo', function () {
    return view('editar_equipo');
});



//PIEZAS

Route::resource('piezas','PiezasController');


//PIEZAS.VIEWS
Route::get('/lista_pieza', function () {
    return view('lista_pieza');
});

Route::get('/agregar_pieza', function () {
    return view('agregar_pieza');
});

Route::get('/editar_pieza', function () {
    return view('editar_pieza');
});

//CLIENTES

Route::resource('clientes','ClientesController');


//CLIENTES.VIEWS
Route::get('/lista_cliente', function () {
    return view('lista_cliente');
});

Route::get('/agregar_cliente', function () {
    return view('agregar_cliente');
});

Route::get('/editar_cliente', function () {
    return view('editar_cliente');
});


//Proveedores

Route::resource('tiendas','TiendasController');


//Proveedores.VIEWS
Route::get('/lista_tienda', function () {
    return view('lista_tienda');
});

Route::get('/agregar_tienda', function () {
    return view('agregar_tienda');
});

Route::get('/editar_tienda', function () {
    return view('editar_tienda');
});

//EMPLEADOS

Route::resource('empleados','EmpleadosController');


//EMPLEADOS.VIEWS
Route::get('/lista_empleado', function () {
    return view('lista_empleado');
});

Route::get('/agregar_empleado', function () {
    return view('agregar_empleado');
});

Route::get('/editar_empleado', function () {
    return view('editar_empleado');
});

resources/views/agregar_empleado.blade.php
<!DOCTYPE html>
<html lang="en">
<title>Agregar empleado</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<!-- Navbar -->

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Agregar</h1>
  <p class="w3-xlarge">Agregar empleado</p>
 <a href="{{route('empleados.index')}}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top" >Atras</a>
</header>

<!-- First Grid -->
<form action="{{ route('empleados.store') }}" method="POST">
    @csrf
    <input type="text" name="nombre" placeholder="Ingrese el nombre" value="{{ old('nombre') }}" required/>
    <input type="text" name="ape" placeholder="Ingrese apellidos" value="{{ old('ape') }}" required/>
    <input type="text" name="sex" placeholder="Ingrese el sexo" value="{{ old('sex') }}" required/>
    <input type="text" name="edad" placeholder="Ingrese la edad" value="{{ old('edad') }}" required/>
    <input type="text" name="tel" placeholder="Ingrese el teléfono" value="{{ old('tel') }}" required/>
    
    <button type="submit">Enviar</button>
</form>



<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

resources/views/agregar_equipo.blade.php
<!DOCTYPE html>
<html lang="en">
<title>Agregar equipo</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<!-- Navbar -->

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Agregar</h1>
  <p class="w3-xlarge">Agregar equipo</p>
 <a href="{{route('equipos.index')}}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top" >Atras</a>
</header>

<!-- First Grid -->
 <form action="{{ route('equipos.store') }}" method="POST">
        @csrf
        <input type="text" name="marca" placeholder="Ingrese la marca" value="{{ old('marca') }}" required/>
        <input type="text" name="modelo" placeholder="Ingrese el modelo" value="{{ old('modelo') }}" required/>
        <input type="text" name="tipo" placeholder="Ingrese el tipo" value="{{ old('tipo') }}" required/>
        
        <input type="text" name="precio" placeholder="Ingrese su precio" value="{{ old('precio') }}" required/>
        <input type="text" name="ref" placeholder="Ingrese la referencia" value="{{ old('ref') }}" required/>
        
        <button type="submit">Enviar</button>
    </form>



<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

resources/views/agregar_pieza.blade.php
<!DOCTYPE html>
<html lang="en">
<title>Agregar pieza</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<!-- Navbar -->

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Agregar</h1>
  <p class="w3-xlarge">Agregar pieza</p>
 <a href="{{route('piezas.index')}}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top" >Atras</a>
</header>

<!-- First Grid -->
<form action="{{ route('piezas.store') }}" method="POST">
    @csrf
    <input type="text" name="marca" placeholder="Ingrese la marca" value="{{ old('marca') }}" required/>
    <input type="text" name="modelo" placeholder="Ingrese el modelo" value="{{ old('modelo') }}" required/>
    <input type="text" name="tipo" placeholder="Ingrese el tipo" value="{{ old('tipo') }}" required/>
    
    <input type="text" name="precio" placeholder="Ingrese su precio" value="{{ old('precio') }}" required/>
    <input type="text" name="ref" placeholder="Ingrese la referencia" value="{{ old('ref') }}" required/>
    
    <button type="submit">Enviar</button>
</form>



<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

resources/views/agregar_tienda.blade.php
<!DOCTYPE html>
<html lang="en">
<title>Agregar proveedor</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<!-- Navbar -->

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Agregar</h1>
  <p class="w3-xlarge">Agregar proveedor</p>
 <a href="{{route('tiendas.index')}}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top" >Atras</a>
</header>

<!-- First Grid -->
<form action="{{ route('tiendas.store') }}" method="POST">
    @csrf
    <input type="text" name="nombre" placeholder="Ingrese el nombre" value="{{ old('nombre') }}" required/>
    <input type="text" name="dire" placeholder="Ingrese dirección" value="{{ old('dire') }}" required/>
    <input type="text" name="tel" placeholder="Ingrese el teléfono" value="{{ old('tel') }}" required/>
    <input type="text" name="ref" placeholder="Ingrese la referencia" value="{{ old('ref') }}" required/>

    
    <button type="submit">Enviar</button>
</form>


<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

resources/views/lista_cliente.blade.php
@extends('plantilla')
<style>body {
    font-family: "Open Sans", sans-serif;
    line-height: 1.25;
  }
  
  table {
    border: 1px solid #ccc;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    table-layout: fixed;
  }
  
  table caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
  }
  
  table tr {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: .35em;
  }
  
  table th,
  table td {
    padding: .625em;
    text-align: center;
  }
  
  table th {
    font-size: .85em;
    letter-spacing: .1em;
    text-transform: uppercase;
  }
  
  @media screen and (max-width: 600px) {
    table {
      border: 0;
    }
  
    table caption {
      font-size: 1.3em;
    }
    
    table thead {
      border: none;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 0;
      position: absolute;
      width: 1px;
    }
    
    table tr {
      border-bottom: 3px solid #ddd;
      display: block;
      margin-bottom: .625em;
    }
    
    table td {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: .8em;
      text-align: right;
    }
    
    table td::before {
      /*
      * aria-label has no advantage, it won't be read inside a table
      content: attr(aria-label);
      */
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }
    
    table td:last-child {
      border-bottom: 0;
    }
  }
  
  </style>
@section('titulo')
    Bienvenido a clientes
@endsection

@section('contenido')
    <h1>Lista de clientes</h1>
    <link rel="stylesheet" href="assets/css/main2.css">
    <nav class="navegacion">
        <a href="{{route('principal')}}">VOLVER A INICIO</a>   
        
    </nav>
    <a href="{{ route('clientes.create')}}">AGREGAR CLIENTES</a>
    @if(session()->has('mensaje'))
    <p style="color: red">{{ session('mensaje') }}</p>
    @endif
    <table class="container">
        <tr>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Ciudad</th>
            <th>Referencia</th>
            <th>Editar | ver ficha</th>
            <th>Eliminar</th>


        </tr>
        @foreach ($clientes as $cliente)
            <tr>
                <td>{{ $cliente->nombre }}</td>
                <td>{{ $cliente->tipo }}</td>
                <td>{{ $cliente->ciudad }}</td>
                <td>{{ $cliente->ref }}</td>
                
                <td><a href="{{ route('clientes.show', $cliente->id)}}">Ver ficha</a> 
                    <br>
                    <a href="{{ route('clientes.edit', $cliente->id)}}">Editar</a></td>
                
                <td>
                    <form action="{{ route('clientes.destroy', $cliente->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit">Eliminar</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/lista_equipo.blade.php
@extends('plantilla')
<style>body {
    font-family: "Open Sans", sans-serif;
    line-height: 1.25;
  }
  
  table {
    border: 1px solid #ccc;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    table-layout: fixed;
  }
  
  table caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
  }
  
  table tr {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: .35em;
  }
  
  table th,
  table td {
    padding: .625em;
    text-align: center;
  }
  
  table th {
    font-size: .85em;
    letter-spacing: .1em;
    text-transform: uppercase;
  }
  
  @media screen and (max-width: 600px) {
    table {
      border: 0;
    }
  
    table caption {
      font-size: 1.3em;
    }
    
    table thead {
      border: none;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 0;
      position: absolute;
      width: 1px;
    }
    
    table tr {
      border-bottom: 3px solid #ddd;
      display: block;
      margin-bottom: .625em;
    }
    
    table td {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: .8em;
      text-align: right;
    }
    
    table td::before {
      /*
      * aria-label has no advantage, it won't be read inside a table
      content: attr(aria-label);
      */
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }
    
    table td:last-child {
      border-bottom: 0;
    }
  }
  
  </style>
@section('titulo')
    Bienvenido a Equipos
@endsection

@section('contenido')
    <h1>Lista de Equipos</h1>
    <link rel="stylesheet" href="assets/css/main2.css">
    <nav class="navegacion">
        <a href="{{route('principal')}}">VOLVER A INICIO</a>   
        
    </nav>
    <a href="{{ route('equipos.create')}}">AGREGAR EQUIPOS</a>
    @if(session()->has('mensaje'))
    <p style="color: red">{{ session('mensaje') }}</p>
    @endif
    <table class="container">
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Tipo</th>
            <th>Precio</th>
            <th>Referencia</th>
            <th>Editar | ver ficha</th>
            <th>Eliminar</th>
        </tr>
        @foreach ($equipos as $equipo)
            <tr>
                <td>{{ $equipo->marca }}</td>
                <td>{{ $equipo->modelo }}</td>
                <td>{{ $equipo->tipo }}</td>
                <td>{{ $equipo->precio }}</td>
                <td>{{ $equipo->ref }}</td>

                
                <td><a href="{{ route('equipos.show', $equipo->id)}}">Ver ficha</a> 
                    <br>
                    <a href="{{ route('equipos.edit', $equipo->id)}}">Editar</a></td>
                
                <td>
                    <form action="{{ route('equipos.destroy', $equipo->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit">Eliminar</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/lista_tienda.blade.php
@extends('plantilla')
<style>body {
    font-family: "Open Sans", sans-serif;
    line-height: 1.25;
  }
  
  table {
    border: 1px solid #ccc;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    table-layout: fixed;
  }
  
  table caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
  }
  
  table tr {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: .35em;
  }
  
  table th,
  table td {
    padding: .625em;
    text-align: center;
  }
  
  table th {
    font-size: .85em;
    letter-spacing: .1em;
    text-transform: uppercase;
  }
  
  @media screen and (max-width: 600px) {
    table {
      border: 0;
    }
  
    table caption {
      font-size: 1.3em;
    }
    
    table thead {
      border: none;
      clip: rect(0 0 0 0);
      height: 1px;
      margin: -1px;
      overflow: hidden;
      padding: 0;
      position: absolute;
      width: 1px;
    }
    
    table tr {
      border-bottom: 3px solid #ddd;
      display: block;
      margin-bottom: .625em;
    }
    
    table td {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: .8em;
      text-align: right;
    }
    
    table td::before {
      /*
      * aria-label has no advantage, it won't be read inside a table
      content: attr(aria-label);
      */
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }
    
    table td:last-child {
      border-bottom: 0;
    }
  }
  
  </style>
@section('titulo')
    Bienvenido a Proveedores
@endsection

@section('contenido')
    <h1>Lista de Proveedores</h1>
    <link rel="stylesheet" href="assets/css/main2.css">
    <nav class="navegacion">
        <a href="{{route('principal')}}">VOLVER A INICIO</a>   
        
    </nav>
    <a href="{{ route('tiendas.create')}}">AGREGAR PROVEEDORES</a>
    @if(session()->has('mensaje'))
    <p style="color: red">{{ session('mensaje') }}</p>
    @endif
    <table class="container">
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Referencia</th>
            <th>Editar | ver ficha</th>
            <th>Eliminar</th>
            
        </tr>
        @foreach ($tiendas as $tienda)
            <tr>
                <td>{{ $tienda->nombre }}</td>
                <td>{{ $tienda->dire }}</td>
                <td>{{ $tienda->tel }}</td>
                <td>{{ $tienda->ref }}</td>
                <td><a href="{{ route('tiendas.show', $tienda->id)}}">Ver ficha</a>
                    <br>
                    <a href="{{ route('tiendas.edit', $tienda->id)}}">Editar</a></td>
                
                <td>
                    <form action="{{ route('tiendas.destroy', $tienda->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit">Eliminar</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/plantilla.blade.php
<!DOCTYPE html>
<html lang="en">
<title>P S I</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>Otras de <br>secciones</b></h3>
  </div>
  <div class="w3-bar-block">
    <a href="{{route('clientes.index')}}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Clientes</a> 
    <a href="{{route('empleados.index')}}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Empleados</a> 
    <a href="{{route('equipos.index')}}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Equipos</a> 
    <a href="{{route('piezas.index')}}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Piezas</a> 
    <a href="{{route('tiendas.index')}}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Proveedores</a> 
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Company Name</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Listas</b></h1>
    <h1 class="w3-xxxlarge w3-text-red"><b>PSI.</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>
  
  
  
   @yield('contenido')
  
  
  
  
  
  
  
  
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>